# action.yaml
name: 'TD TOX Building Automation'
description: 'A GitHub Action that runs TouchDesigner TOX building automations'
inputs:
  build_settings:
    description: 'Path to the buildSettings.json file for the project'
    required: true


runs:
  using: 'composite'
  steps:

    - name: Run TOX Building
      id: run-and-build-tox
      run: python src/tox_builder.py ${{ inputs.build_settings }}
      shell: cmd