# action.yaml
name: 'TD TOX Building Automation'
description: 'A GitHub Action that runs TouchDesigner TOX building automations'
inputs:
  build_settings:
    description: 'Path to the buildSettings.json file for the project'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  
    - name: Fetch the number's square
      id: run-and-build-tox
      run: python src/tox_builder.py
      shell: bash