name: push to version tag
on:
  push:
    tags:
      - v*

jobs:
  Build_tox:
    runs-on: [self-hosted, Windows, TouchDesigner]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true 

      - name: Python TD Builder
        uses: ./
        with:
          build_settings: ./buildSettings.json

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./release/*
